### ISSUE TITLE
sceptre !cmd hooks not executed any more after installing sceptre-resolver-cmd

### ISSUE THREAD

**Issue by RolandOtta** [Sceptre/sceptre-resolver-cmd#1]
after installing the cmd resolver via sudo pip3 install git+https://github.com/lukeplausin/sceptre-resolver-cmd.git sceptre cmd hooks (before_create, before_update, ....) are not executed any more.

after deinstalling sceptre-resolver-cmd the hooks are working again.

**Comment by lukeplausin** [comment]
Hi @RolandOtta

I found the cause of the issue. Sceptre hooks also use the `!cmd` tag, so it seems like the easiest way forwards is to change the name of the sceptre CMD resolver tag.

As of version `1.0.0`, this module will use `!rcmd` instead of `!cmd`, to disambiguate between sceptre hook commands and sceptre resolver commands.
